name: Create Config ZIP
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r config-default.zip config/_default
      - name: Create/Update latest release
        uses: softprops/action-gh-release@v1
        with:
          files: config-default.zip
          tag_name: latest
          name: Latest Config Files
          body: Automated config files bundle